### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CarlaSS1**
Use case: Seizure detected.

### CODE REVIEW

**Comment by 5PK** [comment]
Are we adding multiple files here? Why only a .png?

**Comment by CarlaSS** [comment]
@5PK Luke told me to upload it to the Repo.

**Comment by 5PK** [comment]
@XylarDark @CarlaSS1  This belongs in the google drive. Github should be used for checking in code.

**Comment by CarlaSS** [comment]
Fair enough, I have uploaded the image to the Project Requirements page.

**Comment by 5PK** [comment]
@CarlaSS1 Thanks Carla. Closing this PR.

**Comment by 5PK** [comment]
@CarlaSS1  Make sure to delete this .png from your local as well.

**Pull request closed without merging**
